name: test

on:
  workflow_run:
    workflows: build
    types: completed

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - name: test test
        run: echo 'updated testing abc xyz'

      - name: step 2
        run: echo 'step 2 test'